### ISSUE TITLE
Can't connect to VPN via WireGuard

### ISSUE THREAD

**Issue by ghost** [iodeOS/ota#1]
I cannot connect to VPN via WireGuard. I have tried to turn off battery optimization. I have tried everything but nothing worked(. I am using Xiaomi mi 9

**Comment by eckad158** [comment]
I am using the latest iode version (1.7) and Wireguard works flawlessly on my mi9. However you must not turn on the kernel module (in the wireguard options).

**Comment by vincentvidal** [comment]
wireguard kernel support is now included for all devices, as you may have remarked. The userspace module should work as well. I suppose that this problem is solved.
