### ISSUE TITLE
May I ask why Magic Earth is included?

### ISSUE THREAD

**Issue by EmanuelLoos** [iodeOS/ota#13]
I would like to know what led you to this decision, I mean, you could just include OsmAnd+ instead.

Also please do not use the term "free" that way. Magic Earth may come at no price, but it is by no means free software. The Free Software Foundation actually has stronger requiremants software licenses have to meet than the Open Source Initiative, which splintered off from the FSF to be more acceptable to business. Although the two movements work together their philosophical views do not match: For the OSI the goal of "open sourcing" is that the software gets powerful when more people work on it. There also was an "open source" DRM software (software like Widevine, SafetyNet, etc) that followed that approach to get powerful and though the software was "open source", the version flashed to the devices was not changeable by its users. In that case, however, powerful software means that it restricts users more. "Open Source" does not care about that, it is something for business and the term is used for marketing which is why it is so popular. The FSF on the other hand sees "non-free software" as an issue for society and the solution is "free software" that respects the four essential freedoms defined by the Free Software Foundation. In the eyes of the FSF users deserve freedom and "open source" misses that point. "Open Source" is "free software" without talking about ethics. The term "free" is used as in "freedom", not "at no cost".

By the way: Without the free software movement GNU and the GNU licenses would not exist. Therefore the Linux kernel could not have been released under the terms of the GPL and Wikipedia could not have used the FDL as the license for its articles (used until 2008, then switched to CC-BY-SA with the help of the FSF). The world would be very different.

**Comment by vincentvidal** [comment]
One of our main goal is to build a system easy to apprehend and to use for non techie users, while still being powerful enough for advanced users ; all this with all the constraints that leaving the google world impose. And we want to embed all the basic tools we need in a smartphone, and as such a navigation app. OsmAnd+ is a very good navigation app, much better that ME on many aspects, but : it is more complex to use for basic users, and does not have an very useful feature: real-time traffic conditions. So we decided to include ME, even if it is not free software. We will be more than happy to replace it by a free alternative, when one exists that meets our criteria.
Please note that we also gave the ability to remove preinstalled app, so those unhappy with it can easily switch to another app.
