### ISSUE TITLE
Fairphone 4 fingerprint sensor always on

### ISSUE THREAD

**Issue by SephGER** [iodeOS/ota#16]
Hi,
thanks for this very good ROM. I've installed it on my FP4 and haven't looked back to LineageOS since.
The only problem I have is the fingerprint sensor. It is always on and "listening" for fingerprints, even when the display is off. As I understand it, the phone should only look for fingerprints when the display is on/the button is pressed. Is this a known bug of LineageOS or can this be fixed in iodeOS?

**Comment by vincentvidal** [comment]
It's not a bug, it's a feature. All devices with fingerprint on the back or power button, and many with under display fingerprint, work that way : fingerprint authenticating with screen off awakes the device.
However, as it seems especially annoying for the FP4, we added an option that will be available at next OTA to disable fp authentication when screen is off.

**Comment by SephGER** [comment]
Awesome. Is it already in the 3.0 OTA or will it be in a later one? Can't seem to find it...

**Comment by vincentvidal** [comment]
It is in lockscreen settings (settings -> security -> wheel)

**Comment by SephGER** [comment]
Thanks! Works like a charm!
