### ISSUE TITLE
Bluetooth crash on FP4 iodé 3.0

### ISSUE THREAD

**Issue by subnox** [iodeOS/ota#18]
All is said, I just did the iodé update last night to v3.0 and now when I activate bluetooth, it connect to accessories but after a few seconds shutdown bluetooth again and disconnect.
Thanks for help

**Comment by SephGER** [comment]
I had the same Problem. First you have to deactivate the "Hardware offloading" toggle in the developer settings. After that your phone reboots. Then you have to delete the cache and settings of your bluetooth app.

**Comment by subnox** [comment]
Thanks for your help, I got the bluetooth on, but the sound is not going thrrough my earpods....

What I get also is something like a crash when I try to call someone. It takes like 30s to start the call, maybe you get also the same issue?

**Comment by subnox** [comment]
I reopen it, cause as I said, I got my earpods connected, but dont here anything through it...
