### ISSUE TITLE
Please Provide SHA-256 checksums for your builds

### ISSUE THREAD

**Issue by uriscoes** [iodeOS/ota#2]
Hello iodeOS team @amaurino  and @vincentvidal,

I admire your team's efforts to bring a privacy focused software ROM to the market, thank you! I installed iodeOS quite easily and am very impressed by the quality of the experience.

An important part of privacy products is ensuring the integrity of the product. I could not find checksums of your images. A cryptographic checksum protocol (like SHA-256) allows your users to verify they are running genuine iodeOS software ROMs. 

Please create SHA-256 checksums for your iodeOS images and post the checksums either in GitHub or on your official website so that your users may verify the integrity of their iodeOS images. Doing so is quick, easy, and demonstrates your team's commitment to your privacy ethos.

Thank you very much in advance!

**Comment by teh404guy** [comment]
yup this seems like its an easy thing to do since the command for generating sha-2566 checksums on linux (which i presume they use for building) is literally sha256sum

**Comment by vincentvidal** [comment]
we did, long time ago ;-)
