### ISSUE TITLE
Connection with Bluetooth audio accessories doesn't give any sound FP4 IodéOS v 3.0

### ISSUE THREAD

**Issue by subnox** [iodeOS/ota#20]
So first I had the problem to keep Bluetooth active and get the answer.

Now I can connect the accessories, but the one who are working with sound (Earplugs, Soundbox, Autoradio,...) Are not giving any sound...

For example, if I connect my earplugs with my phone it works but I don't hear anything.
If I connect my phone to my car, same problem, it connects, but I cannot plax anything from the phone...

**Comment by lccimat** [comment]
Hi,
Had the same issue after upgrading to 3.0.
I checked the device logs reguarding BT and found this : 
```
Room cannot verify the data integrity. Looks like you've changed schema but forgot to update the version number. You can simply fix this by increasing the version number.
```

After having cleared datastorage for bluetooth process (go to settings > applications > show all processes > bluetooth > delete both data and cache) every thing were fine (even sound).

**Comment by subnox** [comment]
Thanks for your answer, I did already this. So I can connect my Bluetooth accessorie with my phone. In the car I can call someone and speek with him sound is good. But if I play music, from phone, youtube or spotify, I cannot here anything.
With the earplugs I cannot even make a phone call. I will here the personn but he doesn't and music isnt working.
I delete the storage, cache and the bluetooth accessories again, but there still the same problem.
Thanx in advance

**Comment by subnox** [comment]
Ok so the point is, that I have to do the bluetooth reset procedure every boot again...
But after that, it is working.
Thanks
