### ISSUE TITLE
VoWifi  not working on FP3

### ISSUE THREAD

**Issue by yvmuell** [iodeOS/ota#21]
VoWiFi not functioning (Build RQ3A.211001.001 dev-keys). 

Dialing `*#*#4636#*#*` Phone Information > click on three dots top right corner > IMS Service Status > "IMS Registration:  Registered"/ VoWifi: not available/VoLTE: available

Settings > Network & Internet > Mobile Network > VoLTE is enabled

Settings > Network & Internet > Mobile Network > Advanced > WiFi Calling is enabled

It was working on FPOS.

**Comment by starbrights** [comment]
It's not expected to work, as non of the custom Roms can do that (at least for Samsung) - because these is closed source. If you need that, you have to go back to stock - correct me if I am wrong.

**Comment by vincentvidal** [comment]
Effectively it does not work on FP3. These features (VoLte and VoWifi) require to include some proprietary blobs into the system, which may or may not work. For samsung in particular, it never worked.

**Comment by Andronym** [comment]
VoWifi & VoLte both works flawlessly on FP3+ with Iodé 3.1 Build SQ3A-220705.003.A1 dev-keys!
