### ISSUE TITLE
FP4 (Fairphone 4) heat issues

### ISSUE THREAD

**Issue by Blockmaster2706** [iodeOS/ota#22]
I have recently bought a Fairphone 4 which arrived yesterday. First thing i did after getting it was unlocking the bootloader and installing iodé OS, as it seemed to be the best custom rom choice currently available.

Now, I did not properly test the phone with the stock ROM, to be fair, but I have noticed that the phone gets unusually warm even with just basic usage like browsing the web using the browser iodé comes with. This heat seems to have an effect on battery life and performance, too, as it sometimes gets so hot that it looses battery very quickly and starts lagging a bit.

I have also tried playing COD Mobile on the phone, as i thought that performance wise the phone should be able to handle it, but after just a single round of a couple minutes the phone was so hot that it was noticably laggy and i was afraid to keep using it, in fear that it might overheat and cause damage.

Now my question is, is this expected behaviour with the FP4, or is there anything i can do to fix this?
I would prefer not having to reinstall iodé or having to install another ROM, if possible, but I could do so if everything else fails.

Thanks in advance for any help I might receive

Edit: I have since installed the newest version of /e/OS on my device and have had no such issues. Might be worth investigating on your side?

**Comment by vincentvidal** [comment]
iodéOS for FP4 have been downloaded hundreds of times, and we never heard about such a problem. Maybe you could try the latest release (3.1), and send a logcat if the problem persists.
