### ISSUE TITLE
initial installation procedure for sony xa2 pioneer in the wiki

### ISSUE THREAD

**Issue by githluapb** [iodeOS/ota#23]
The Wiki says [here](https://github.com/iodeOS/ota#how-to-flash-sony-xperia-xa2-xz1-xz2-xz3=), I cite:

>Following your device:
>XA2:
>fastboot flash boot_a [boot-pioneer.img](https://github.com/iodeOS/ota/releases/tag/v3-pioneer)
>fastboot flash boot_b [boot-pioneer.img](https://github.com/iodeOS/ota/releases/tag/v3-pioneer)

The link does not provide a boot-pioneer.img, but recovery images instead:
> iode-3.0-20220601-pioneer-recovery.img 24 MB 02 Jun 2022
> iode-3.0-20220601-pioneer-recovery.img.sha256 116 Bytes 02 Jun 2022
> iode-3.0-20220601-pioneer.zip 904 MB 02 Jun 2022
> iode-3.0-20220601-pioneer.zip.sha256 96 Bytes 02 Jun 2022
> Source code (zip) 12 Apr 2022
> Source code (tar.gz) 12 Apr 2022

Before flashing the wrong img file to the wrong partition - what needs to be updated in this instruction to work and to be consistent?

**Comment by vincentvidal** [comment]
Right: the wording should be changed. In fact on some devices, the boot and recovery are in the same image, which may lead to some confusion. We decided to stick to the term "recovery" for the files, so we should (and will) do the same for the installation instructions.
