### ISSUE TITLE
S9 update 2.6 -> 2.7: virtual keyboard missing for unlock the encryption

### ISSUE THREAD

**Issue by pbiering** [iodeOS/ota#26]
after upgrading from 2.6 to 2.7 the virtual keyboard is missing to unlock the encryption.

Had to connect an USB keyboard.

_Have to downgrade to 2.6 until fixed._ -> not working, see below

**Comment by pbiering** [comment]
Can't downgrade, encryption PIN is no longer working when booting 2.6 -> need help now and have to carry USB keyboad with me all the time :-(

**Comment by pbiering** [comment]
Hmm, are there only 2 out of (?how many) S9 affected after upgrade from 2.6 to 2.7
- how many S9 have still 2.6 installed and are on risk running update to 2.7 and turning into "unusable phone" status if no USB-C to-go adapter + USB keyboard/keypad is nearby?
- how many S9 have successfully upgraded from 2.6 to 2.7 without any issue?
- in case it stays on the 2 phones...what is the (historical) pattern of this phones running into such issue?
  - as 2.6 was released end of July, have this 2 phones now carrry USB-C to-go + keypad for the next 3 months...?
  - how can at least I support to find the root cause?

**Comment by vincentvidal** [comment]
We are investigating the issue.

**Comment by vincentvidal** [comment]
A hotfix build (buld number 20221024) has been published for all samsung 9 devices running iodéOS v2. They must be sideloaded by adb.
For starlte (S9) : https://github.com/iodeOS/ota/releases/tag/v2-starlte
For star2lte (S9+) : https://github.com/iodeOS/ota/releases/tag/v2-star2lte
For crownlte (Note 9) : https://github.com/iodeOS/ota/releases/tag/v2-crownlte

**Comment by pbiering** [comment]
Solution solved by provided hotfix - thank you!
