### ISSUE TITLE
Release beta .zip file on github

### ISSUE THREAD

**Issue by TheRealGramdalf** [iodeOS/ota#28]
I also asked this in the XDA thread for my device, but figured it should go here as well.

I believe due to my phone being rooted (magisk), it was caught in a bootloop when updating to 3.3 from 3.2. The issue is that since I no longer have access to my phone, I can't manually extract the boot image from the zip, patch it from another android device, and flash it manually. More details here: https://forum.xda-developers.com/t/rom-xz1-12-0-iodeos-lineageos-19-1-microg-adblocker-17-10-2022.4129997/page-8

I suggest that the zip file be available somewhere, similar to the releases here on OTA. That way I can flash the correct boot image and my phone will be working again, and this won't be an issue in the future.

**Comment by Suznyan** [comment]
There're all here: https://github.com/vincentvidal/iode_ota/releases/
Make sure to click on Show all assets

**Comment by TheRealGramdalf** [comment]
Thanks!
