### ISSUE TITLE
Speaker clip/distortion

### ISSUE THREAD

**Issue by James1599** [iodeOS/ota#3]
Tested on: XZ2  (akari) H8266
OS: Iode 1.2, (20210525), Iode 2 (20210617)

Problem: Speaker clipping on high volume in all apps and system sounds.

Reproduce: Just play any audio or open youtube and set volume to 70%+

**Comment by vincentvidal** [comment]
Our active issue tracker is on gitlab, sory for not having answered. I suppose your problem is solved now, or you switched to another rom...
