### ISSUE TITLE
Unable to update using "Updater" app

### ISSUE THREAD

**Issue by uriscoes** [iodeOS/ota#4]
Phone: Teracube 2e 

iodeOS build number: iodeos_2e-userdebug 10 QQ3A.200805.001 eng.vince.20210616.111243 dev-keys

Recovery Image: OEM provided

I was unable to successfully apply the June 19th iodeOS. 1.2 update. When attempting to apply the update the phone appears to boot to the "update screen" with the iodeOs theme and circlet icon. However 1/3rd of the way through the update the icon changes to the green android alien and says "error!". 

The phone reboots to system. 

How can I fix this issue or manually apply the update?

**Comment by teh404guy** [comment]
here are the steps to manually flash the OTA
1. send the OTA update img file from the releases section of this github
2. download the twrp img also available in the release section, then flash it using the flahs tool of your phone
3. enter into recovery mode, by doing the recovery combo, or if you have the adb drivers necessary and the adb utils you can just 'adb reboot recovery'
4. while in recovery go to the install section, there you can access either the /sdcard or /data partition and you will look for your img file and then install it
while ive never used iodé, ive had experience with lineage (which iodé is based on), idk if the twrp is built with partition encryption in mind, but if you cant access /data or /sdcard then you might ask the devs of iodé to give you a build of twrp with encryption enabled

**Comment by saxofooon** [comment]
Hi, great work here. Unfortunately there is little to no installation instructions. I successfully installed iode 1.4 on teracube 2e. The downloader wants to update to 2.3, then boots into twrp recovery, but I cannot find the 2.3 zip. In /data/data and /sdcard are only a lot of cryptic folder names?

**Comment by Satlinker** [comment]
Similar OTA update problem from 2.3 to 2.4 on old Teracube. iode logo appears and after a while reboot with options "try again" and "factory reset". Message: Version 2.3, Can't load android system. Your data may be corrupt...

**Comment by Satlinker** [comment]
Disaster: Sideloading doesn't help. Installation of recovery 2.4 and iode-2.4-20220401-2e.zip works fine (install completed with status 0), but still booting stops after logo and reboot to factory reset option.

C:\adb>adb sideload iode-2.4-20220401-2e.zip
* daemon not running; starting now at tcp:5037
* daemon started successfully
serving: 'iode-2.4-20220401-2e.zip'  (~94%)    adb: failed to read command: No error

**Comment by vincentvidal** [comment]
We are fixing that issue, which appears on a few devices. New builds will be up in a couple of days that will permit to recover data for those who did not format. If you want a quick update, join the beta testing group, and update will probably be available tomorrow morning.
