### ISSUE TITLE
IMS Not Working Sony Xperia XZ3

### ISSUE THREAD

**Issue by Naisntin** [iodeOS/ota#6]
VoLTE and VoWiFi are not functioning. Using the dialer >`*#*#4636#*#*`> Phone Information > click on three dots top right corner > IMS Service Status > "IMS Registration: Not Registered".

Settings > Network & Internet > Mobile Network > VoLTE is enabled 

Settings > Network & Internet > Mobile Network > Advanced > WiFi Calling is enabled

I confirmed with my mobile operator that the phone is fully provisioned and registered on the network and that it was "not an issue with their network".

Build: iodeos_akatsuki-userdebug 11 RQ3A.210705.001 eng.vince.20210729.170325 dev-keys

**Comment by vincentvidal** [comment]
Our active issue tracker is on gitlab, sorry for not having answered earlier. Please open an issuer there if you still have problems.
