### ISSUE TITLE
Signature verification fails on newest iodeOS 2.x for Samsung Galaxy S9+

### ISSUE THREAD

**Issue by keesvanbochove** [iodeOS/ota#7]
After installing the recovery image (https://github.com/iodeOS/ota/releases/download/v2-star2lte/recovery-star2lte.img) succesfully on a Samsung Galaxy S9+, rebooting into recovery mode (`adb reboot recovery`), selecting `Apply update from ADB` on the recovery menu on the phone and sideloading (`adb sideload  iode-2.0-20210729-star2lte.zip`) the provided ZIP file (https://github.com/iodeOS/ota/releases/download/v2-star2lte/iode-2.0-20210729-star2lte.zip), the transfer to the phone succeeds (adb shows a progress indicator and ends with `Total xfer: 1.00x`), but the phone throws an error and refuses to install the package:

```
Now send the package you want to apply
to the device with "adb sideload <filename>"...
Finding update package...
Opening update package...
Verifying update package...
E:failed to verify whole-file signature
Update package verification took 58.2 s (result 1).
E:Signature verification failed
E:error 21 

Install from ADB completed with status 2.
Installation aborted.#1
```

This is the metadata file from inside the ZIP:
```
ota-property-files=metadata:69:342         
ota-required-cache=0
ota-type=BLOCK
post-build=samsung/star2ltexx/star2lte:10/QP1A.190711.020/G965FXXUCFTK1:user/release-keys
post-build-incremental=eng.vince.20210729.171508
post-sdk-level=30
post-security-patch-level=2021-07-05
post-timestamp=1627571640
pre-device=star2ltexx,star2lteks,star2lte
```

**Comment by Mabisi** [comment]
Hi, may I ask how did you install the recovery image?

**Comment by keesvanbochove** [comment]
I installed it using Odin v3.14.1.

**Comment by vincentvidal** [comment]
Our issue tracker (the one that we closely follow and reference in our communication) is at gitlab.com/iode/ota, that's why you did not yet receive an answer, sorry.
I suppose you found a solution, as we now provide a recovery for each build we publish.
